### ISSUE TITLE
Not able to detect my launchpad

### ISSUE THREAD

**Issue by PastaLittleEggo** [nimaid/LPHK#5] opened 2019-03-13 01:24 UTC
I have my novation launchpad MK2 plugged into my galliumos linux laptop, and for some reason, it can't be detected. here is the log:

**chrx@chrx:~/Desktop/LPHK-master$ python3 LPHK.py
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib conf.c:3523:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib conf.c:3523:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default
Traceback (most recent call last):
  File "LPHK.py", line 58, in <module>
    main()
  File "LPHK.py", line 56, in main
    shutdown()
  File "LPHK.py", line 49, in shutdown
    os.execv(sys.executable, ["\"" + sys.executable + "\""] + sys.argv)
FileNotFoundError: [Errno 2] No such file or directory**

Here is what it looks like when I type `lsusb`

**chrx@chrx:~/Desktop/LPHK-master$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 8087:0a2a Intel Corp. 
Bus 001 Device 002: ID 04f2:b567 Chicony Electronics Co., Ltd 
Bus 001 Device 015: ID 1235:0069 Focusrite-Novation 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub**

Any help is appreciated. Thank you.

**Comment by PastaLittleEggo** [comment] 2019-03-13 22:43
Update:
Trying to install dependencies again, and I realized that I get this error:
E: Unable to locate package python3-distutils

**Comment by qCamm** [comment] 2019-04-19 04:30
Did you eventually resolve this issue?

**Comment by PastaLittleEggo** [comment] 2019-04-28 19:52
I have not yet. I think it may have to do with either me, or galliumOS. Pretty sure that it is me. I am still looking into it.

**Comment by nimaid** [comment] 2019-05-08 21:35
@PastaLittleEggo First, let me address the prerequisite install error: I have never used galliumOS, but it seems that the `python3-distutils` package is either not present in the repositories for your OS, or more likely, that it is named something slightly different. If you could please run the following command and post the output:
`sudo apt-get update && sudo apt-cache search distutils`

However, it seems that the error in your original post may not be related to the `python3-distutils` package. It seems more likely to be that you are missing the `libasound2-plugins` package. Try running the following, then LPHK. It will likely still break, but it may break in a different way that can help me fix it, so let me know exactly what happens.

**Comment by matt-goingout** [comment] 2019-05-22 12:48
Hi, getting the same error with libasound_module_conf_pulse.so and no lauchpad detected (have a lauchpad mini)-> I'm running ubuntu 18.04 LTS

apt install libasound2-plugins tells me:

"libasound2-plugins is already the newest version (1.1.1-1ubuntu1)."

aconnect -i
client 0: 'System' [type=kernel]
    0 'Timer           '
    1 'Announce        '
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 20: 'Launchpad Mini' [type=kernel,card=1]
    0 'Launchpad Mini MIDI 1'

and I can see midi messages from the launchpad via aseqdump

searcing for distutils:

python-pbr - inject useful and sensible default behaviors into setuptools - Python 2.x
python-pbr-doc - inject useful and sensible default behaviors into setuptools - doc
python-setuptools - Python Distutils Enhancements
python-setuptools-doc - Python Distutils Enhancements (documentation)
python3-d2to1 - Python3 support for distutils2-like setup.cfg files as package metadata
python3-distutils - distutils package for Python 3.x
python3-pbr - inject useful and sensible default behaviors into setuptools - Python 3.x
python3-setuptools - Python3 Distutils Enhancements
jcc - code generator producing a Python extension from Java classes
pypy-bdist-nsi - Create NSIS windows installers for Python modules (PyPy)
pypy-setuptools - PyPy Distutils Enhancements
python-bdist-nsi - Create NSIS windows installers for Python modules (Python 2)
python-d2to1 - Python support for distutils2-like setup.cfg files as package metadata
python-distlib - low-level components of python distutils2/packaging
python-distutils-extra - enhancements to the Python build system
python-fswrap - unified object oriented interface to file system objects
python-instant - simple inlining of C/C++ code in Python 2
python-pkginfo - Python 2.x module to query metadata from packages
python-pkginfo-doc - Python module to query metadata from packages documentation
python-pytest-runner - Invoke py.test as distutils command with dependency resolution - Python 2.x
python-sip-dev - Python/C++ bindings generator development files
python-stdeb - Python to Debian source package conversion utility
python-stsci.distutils - Python packaging utilities for STScI's packages
python3-bdist-nsi - Create NSIS windows installers for Python modules (Python 3)
python3-distlib - low-level components of python distutils2/packaging
python3-distutils-extra - enhancements to the Python3 build system
python3-fswrap - unified object oriented interface to file system objects (Python 3)
python3-instant - simple inlining of C/C++ code in Python 3
python3-pkginfo - Python 3.x module to query metadata from packages
python3-pytest-runner - Invoke py.test as distutils command with dependency resolution - Python 3.x
python3-sip-dev - Python 3/C++ bindings generator development files
python3-stdeb - Python to Debian source package conversion plugins for distutils
python3-stsci.distutils - Python3 packaging utilities for STScI's packages
mgltools-opengltk - Opengltk Python extension

**Comment by duncte123** [comment] 2019-11-23 08:40
Same issue here and I do have `libasound2-plugins` installed

**Comment by nimaid** [comment] 2019-11-28 16:42
Okay everyone, on my setup where I reproduced the issue (Ubuntu 19.10) it was due to issues with the exact location of the `libasound_module_conf_pulse.so` file. A symlink fixed it. Not sure if this is a permanent fix but it's a start.

1. Before trying this solution, make a note of the location it's trying to find `libasound_module_conf_pulse.so`. This should be in the errors after `Hello from the pygame community`. It's probably `cd /usr/lib/x86_64-linux-gnu/`
2. Next, search for the file by doing `sudo find / -name libasound_module_conf_pulse.so`. If you find an entry like `ABOVE_PATH/alsa-lib/libasound_module_conf_pulse.so`, you should try the next step. Otherwise, post all your output here.
3. If the above 2 steps were done successfully, run the command `sudo ln -s ABOVE_PATH/alsa-lib/libasound_module_conf_pulse.so ABOVE_PATH/libasound_module_conf_pulse.so`. Try running LPHK now, and post your results.

**Comment by duncte123** [comment] 2019-11-28 19:26
Works fine right now but there is one issue where if you start LPHK before plugin in the launchpad it will throw the following error 
```
duncte123@duncte123:~/Desktop/LPHK$ conda activate LPHK
(LPHK) duncte123@duncte123:~/Desktop/LPHK$ python LPHK.py 
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib pcm.c:8306:(snd_pcm_recover) underrun occurred
```
I also feel like it would be a simple if-statement to just check for `/usr/lib/x86_64-linux-gnu/alsa-lib/libasound_module_conf_pulse.so` and use `/usr/lib/x86_64-linux-gnu/libasound_module_conf_pulse.so` if it is not present 

last but not least 
![image](https://user-images.githubusercontent.com/8843386/69828628-db8c2300-121c-11ea-9070-228cc5b44bc8.png)

it seems to do this for all keys when loading the default layout and the media controls don't seem to work either.

**Comment by nimaid** [comment] 2019-12-01 06:06
@duncte123 Neither of those things can be fixed in Python, those messages are coming from the ALSA driver. I need to do more research, stay tuned.

**Comment by nimaid** [comment] 2019-12-01 22:34
> last but not least
> ![image](https://user-images.githubusercontent.com/8843386/69828628-db8c2300-121c-11ea-9070-228cc5b44bc8.png)
> 
> it seems to do this for all keys when loading the default layout and the media controls don't seem to work either.

This is a separate issue with root privileges on linux, see #14 .

**Comment by PastaLittleEggo** [comment] 2020-01-25 00:53
Hi everyone. My computer died a long time ago, so I haven't been able to update this post in a long time. It seems that there was another problem going on, so I will not close it unless nimaid feels like it should be closed.

**Comment by lyiriyah** [comment] 2020-03-07 20:42
My LPHK wants to find libasound_module_conf_pulse.so in /usr/lib/alsa-lib/ on Ubuntu 18.04.

**Comment by kartikay-bagla** [comment] 2020-10-05 19:30
> My LPHK wants to find libasound_module_conf_pulse.so in /usr/lib/alsa-lib/ on Ubuntu 18.04. 

I just switched from Windows to Pop. And I was getting the same thing. What worked for me was linking the entire alsa-lib folder from the `x86_64-linux-gnu` folder by running:

```
cd /usr/lib
sudo ln -s x86_64-linux-gnu/alsa-lib/ alsa-lib
```

Also I am by no means an expert (let alone average) at linux, but here is the process I followed to get up and running with this on a fresh install of Pop_OS 20.04

1. First we start off with python3.7 [resource](https://askubuntu.com/questions/682869/how-do-i-install-a-different-python-version-using-apt-get)
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.7
```

then we install tkinter with:
```
sudo apt-get install python3.7-tk
```

followed by the sound thing (idk what it is)
```
sudo apt-get install -y libasound2-plugins
```

after which we link our installed library to where we actually expect it to be with
```
cd /usr/lib
sudo ln -s x86_64-linux-gnu/alsa-lib/ alsa-lib
```

finally you can install the dependencies with
```
cd LPHK_LOCATION
python3.7 -m pip install -r INSTALL/requirements.txt
```

try running LPHK now with
```
python3.7 LPHK.py
```

Hopefully this helps out someone.

**Comment by duncte123** [comment] 2021-02-18 20:33
Closing due to inactivity

**Closed by duncte123** 2021-02-18 20:33 UTC
