### ISSUE TITLE
Wrong keybinds?

### ISSUE THREAD

**Issue by zinixyt** [nimaid/LPHK#11] opened 2019-08-06 12:57 UTC
Today i made a layout to play fortnite with my launchpad mini and i had two problems:

I assigned "TAP d" to a key and when i ran it... it muted the sound of the computer;
I assigned "TAP g" to another key and it started playing music in spotify.

I once tested this and i had no problems.

My OS: Windows 10

**Comment by nimaid** [comment] 2019-09-18 19:48
Wow, that is weird. Could you please open (LPHK directory)/utils/GET_KEYCODES.py while using the launchpad macros, and paste the output?

**Comment by RogbonolYT** [comment] 2019-09-29 13:27
Sorry for late response, here is the output:
`Name: 'D', Scan Code: '57376'`
`Name: 'G', Scan Code: '57378'`

**Comment by nimaid** [comment] 2019-11-17 20:21
You want to use a capital D, it seems. `TAP D`. Please reply and let me know if this solves your issue.

**Comment by nimaid** [comment] 2019-11-30 01:35
@RobonolYT Please respond to this issue promptly.

**Comment by nimaid** [comment] 2019-12-10 22:38
I am still uncertain of the exact nature of this issue. However, a re-write of the keyboard functions using `pyautogui` is coming. If the issue is not already resolved, this may fix it.

**Comment by duncte123** [comment] 2021-02-18 20:39
Rewrite has happened, closing this issue

**Closed by duncte123** 2021-02-18 20:39 UTC
