### ISSUE TITLE
Is it removed or what?

### ISSUE THREAD

**Issue by RewardedIvan** [nimaid/LPHK#91] opened 2021-04-25 14:11 UTC
![image](https://user-images.githubusercontent.com/67065165/115996750-45af2000-a5e9-11eb-9ad6-d3c5376db2ea.png)
![image](https://user-images.githubusercontent.com/67065165/115996756-4942a700-a5e9-11eb-92c3-58fe58304f52.png)

**Comment by duncte123** [comment] 2021-04-25 14:13
Simple is not listed in the supported commands there because it only supports keyboard keys

**Comment by RewardedIvan** [comment] 2021-04-25 14:17
![image](https://user-images.githubusercontent.com/67065165/115996975-10ef9880-a5ea-11eb-8b76-e5c76465708e.png)

**Comment by RewardedIvan** [comment] 2021-04-25 14:22
> Simple is not listed in the supported commands there because it only supports keyboard keys

![image](https://user-images.githubusercontent.com/67065165/115997145-c884aa80-a5ea-11eb-822f-4096d781801a.png)

**Comment by duncte123** [comment] 2021-04-26 07:39
what version of LPHK are you using? I cannot reproduce this in the latest release (version 0.3.1).

**Comment by RewardedIvan** [comment] 2021-04-30 11:11
> what version of LPHK are you using? I cannot reproduce this in the latest release (version 0.3.1).

0.3.0

**Comment by duncte123** [comment] 2021-04-30 13:00
> > what version of LPHK are you using? I cannot reproduce this in the latest release (version 0.3.1).
> 
> 0.3.0

Then it is correct that you are experiencing this bug, as it was fixed in 0.3.1

**Closed by duncte123** 2021-04-30 13:00 UTC
