### ISSUE TITLE
LPHK Crash when redetecting Launchpad

### ISSUE THREAD

**Issue by duncte123** [nimaid/LPHK#15] opened 2019-11-09 08:35 UTC
OS: Ubuntu 18.04
Launchpad: MK2
Python versions (python --version)
System: Python 2.7.15+
Conda: Python 3.7.5

When pressing connect to launchpad the following error occurs, when switching usb ports and pressing redetect the program crashes 
![image](https://user-images.githubusercontent.com/8843386/68525659-1c56e300-02d4-11ea-9187-2e766f84c0de.png)

Program output (full output):
```
duncte123@duncte123 ~> bash
duncte123@duncte123:~$ conda activate LPHK
(LPHK) duncte123@duncte123:~$ python --version
Python 3.7.5
(LPHK) duncte123@duncte123:~/Desktop/LPHK$ git pull
remote: Enumerating objects: 58, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 53 (delta 37), reused 35 (delta 19), pack-reused 0
Unpacking objects: 100% (53/53), done.
From github.com:nimaid/LPHK
   d52345a..cc4d1ca  master     -> origin/master
Updating d52345a..cc4d1ca
Fast-forward
 README.md                        | 304 +++++++++++++++++++++------------------
 install_beta/install_windows.bat |  57 ++++----
 window.py                        |  15 +-
 3 files changed, 210 insertions(+), 166 deletions(-)
(LPHK) duncte123@duncte123:~/Desktop/LPHK$ python LPHK.py 
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib conf.c:3558:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so (/usr/lib/alsa-lib/libasound_module_conf_pulse.so: libasound_module_conf_pulse.so: cannot open shared object file: No such file or directory)
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fa47d9ed740 (most recent call first):
Aborted (core dumped)
(LPHK) duncte123@duncte123:~/Desktop/LPHK$ 

```

LSUSB output:
```
duncte123@duncte123 ~> lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 8087:0a2b Intel Corp. 
Bus 001 Device 002: ID 0bda:58d2 Realtek Semiconductor Corp. 
Bus 001 Device 004: ID 1235:0069 Focusrite-Novation 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
duncte123@duncte123 ~> 
```

**Comment by nimaid** [comment] 2019-11-17 20:11
@duncte123 Please try installing the package `libasound2-plugins` using `sudo apt-get install libasound2-plugins` and report your results, including `apt-get` output.

**Comment by nimaid** [comment] 2019-11-17 20:29
Duplicate of #5

**Comment by nimaid** [comment] 2019-11-17 20:30
Please post all future replies in Issue #5.

**Closed by nimaid** 2019-11-17 20:30 UTC
